project:
  type: book

book:
  title: 'Documentation'
  subtitle: 'oFeeds'
  author:
  - name: Hauke Roggenkamp
    email: Hauke.Roggenkamp@unisg.ch
    orcid: 0009-0005-5176-4718
    corresponding: true
    affiliations:
      - name: Institute of Behavioral Science and Technology, University of St. Gallen
        address: Torstrasse 25
        city: St. Gallen
        state: Switzerland
        postal-code: 9000
  date: now
  date-format: long
  sharing: 
    - twitter
    - linkedin
  license: 'MIT'
  repo-url: 'https://github.com/Howquez/oFeeds'
  chapters:
    - index.qmd
    - oTree.qmd
    - session.qmd
    - oCom.qmd
    - oNovitas.qmd
    - oTweet.qmd
    - prolific.qmd
    - misc.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



